import { getElement, getAllElements } from "../utils/dom";

export const elements = {
    overlay: getElement<HTMLDivElement>(".overlay"),
    askForNotifications: getElement<HTMLDivElement>(".askForNotifications"),
    enableNotificationsBtn: getElement<HTMLButtonElement>(
    ".enableNotificationsBtn",
    ),
    closeNotiPopup: getElement(".closeNotiPopup"),
    sidebar: getElement<HTMLDivElement>(".sidebar"),
    sidebarBtns: getAllElements<HTMLButtonElement>(".sidebar button"),
    hamburgerBtn: getElement<HTMLButtonElement>(".hamburgerBtn"),
    whatToFocusOn: getElement<HTMLDivElement>(".whatToFocusOn"),
    focusOnList: getElement<HTMLUListElement>(".focusOnList"),
    header: getElement<HTMLHeadElement>(".header"),
    currentDate: getElement<HTMLDivElement>(".currentDate"),
    dynamicGreeting: getElement<HTMLHeadingElement>(".greeting"),
    searchDiv: getElement<HTMLDivElement>(".searchDiv"),
    searchBar: getElement<HTMLInputElement>(".searchBar"),
    searchResultsMenu: getElement<HTMLDivElement>(".searchResultsMenu"),
    dashboardBtn: getElement<HTMLButtonElement>(".dashboardBtn"),
    calendarBtn: getElement<HTMLButtonElement>(".calendarBtn"),
    settingsBtn: getElement<HTMLButtonElement>(".settingsBtn"),
    dashboardContent: getElement<HTMLDivElement>(".dashboardContent"),
    dashboardHeader: getElement<HTMLDivElement>(".dashboardHeader"),
    agentBtn: getElement<HTMLButtonElement>(".agentBtn"),
    aiToggle: getElement<HTMLInputElement>("#aiToggle"),
    aiOptionsDiv: getElement<HTMLDivElement>(".aiOptionsDiv"),
    /** aiOptionsList: getElement<HTMLUListElement>(".aiOptionsList"), */
    prioritySuggestionOption: getElement<HTMLButtonElement>(
    ".prioritySuggestionOption",
    ),
    /** scheduleSuggestionOption: getElement<HTMLButtonElement>(
     ".scheduleSuggestionOption",
    ),
    riskReportOption: getElement<HTMLButtonElement>(".riskReportOption"), */
    aiDiv: getElement<HTMLElement>(".aiDiv"),
    decrastinatorBtn: getElement<HTMLButtonElement>(".decrastinatorBtn"),
    closeDecrastinatorBtn: getElement<HTMLButtonElement>(".closeDecrastinatorBtn"),
    customizeBtn: getElement<HTMLButtonElement>(".customizeBtn"),
    customizeDiv: getElement<HTMLDivElement>(".customizeDiv"),
    customizeBgOptions: getAllElements<HTMLButtonElement>(
    ".customizeBgOptions button",
    ),
    expandMiniAnalyticsBtn: getElement<HTMLButtonElement>(".expandMiniAnalyticsBtn"),
    miniAnalytics: getElement<HTMLDivElement>(".miniAnalytics"),
    /* momentumItems: getElement<HTMLUListElement>(".momentumItems"),
    momentumDivFooter: getElement<HTMLDivElement>(".momentumDivFooter"),
    workAreaSplit: getElement<HTMLDivElement>(".workAreaSplit"), */
    section1: getElement<HTMLDivElement>(".section1"),
    section2: getElement<HTMLDivElement>(".section2"),
    toDoList: getElement<HTMLUListElement>(".toDoList"),
    toDoListHeader: getElement<HTMLDivElement>(".toDoListHeader"),
    taskSortSelector: getElement<HTMLSelectElement>(".taskSortSelector"),
    taskViewSelector: getElement<HTMLSelectElement>(".taskViewSelector"),
    addBtn: getElement<HTMLButtonElement>(".addBtn"),
    taskCreationDiv: getElement<HTMLDivElement>(".taskCreationDiv"),
    /** actualTaskCreation: getElement<HTMLDivElement>(".actualTaskCreation"), */
    taskInput: getElement<HTMLInputElement>(".taskInput"),
    /** taskAttrCreation: getElement<HTMLDivElement>(".taskAttrCreation"), */
    taskPrioritySelector: getElement<HTMLSelectElement>(".taskPrioritySelector"),
    taskDateInput: getElement<HTMLInputElement>(".taskDateInput"),
    taskTimeInput: getElement<HTMLInputElement>(".taskTimeInput"),
    taskStatusSelector: getElement<HTMLSelectElement>(".taskStatusSelector"),
    taskRecurrenceSelector: getElement<HTMLSelectElement>(
    ".taskRecurrenceSelector",
    ),
    blockedByDiv: getElement<HTMLDivElement>(".blockedByDiv"),
    blockedByInput: getElement<HTMLInputElement>(".blockedByInput"),
    /** blockedByList: getElement<HTMLUListElement>(".blockedByList"),
    addAndCancelButtons: getElement<HTMLDivElement>(".addAndCancelButtons"), */
    cancelTaskCreationBtn: getElement<HTMLButtonElement>(".cancelTaskCreationBtn"),
    addTaskBtn: getElement<HTMLButtonElement>(".addTaskBtn"),
    taskList: getElement<HTMLUListElement>(".taskList"),
    noTasksYetAlert: getElement<HTMLDivElement>(".noTasksYetAlert"),
    dropZones: getElement<HTMLDivElement>(".dropZones"),
    toDoDropZone: getElement<HTMLDivElement>(".toDoDropZone"),
    inProgressDropZone: getElement<HTMLDivElement>(".inProgressDropZone"),
    allDoneDropZone: getElement<HTMLDivElement>(".allDoneDropZone"),
    focusTimer: getElement<HTMLDivElement>(".focusTimer"),
    timerOptionsDropdown: getElement<HTMLSelectElement>(".timerOptionsDropdown"),
    taskSelectionDropdown: getElement<HTMLSelectElement>(".taskSelectionDropdown"),
    currentFocusedTask: getElement<HTMLDivElement>(".currentFocusedTask"),
    /** timerMinutesDiv: getElement<HTMLDivElement>(".timerMinutesDiv"), */
    timerProgressRing: getElement<HTMLDivElement>(".timerProgressRing"),
    timerMinutes: getElement<HTMLDivElement>(".timerMinutes"),
    timerButtons: getElement<HTMLDivElement>(".timerButtons"),
    lengthButtons: getAllElements<HTMLButtonElement>(".timerLengthOptions button"),
    startTimerBtn: getElement<HTMLButtonElement>(".startTimerBtn"),
    pauseTimerBtn: getElement<HTMLButtonElement>(".pauseTimerBtn"),
    restartTimerBtn: getElement<HTMLButtonElement>(".restartTimerBtn"),
    themeBtn: getElement<HTMLButtonElement>(".themeBtn"),
    /** notes: getElement<HTMLDivElement>(".notes"), */
    addBtn2: getElement<HTMLButtonElement>(".addBtn2"),
    notesList: getElement<HTMLUListElement>(".notesList"),
    /** notesHeader: getElement<HTMLHeadingElement>(".notesHeader"), */
    noNotesYetAlert: getElement<HTMLDivElement>(".noNotesYetAlert"),
    noteCreationDiv: getElement<HTMLDivElement>(".noteCreationDiv"),
    noteInput: getElement<HTMLInputElement>(".noteInput"),
    noteColorOptions: getAllElements<HTMLButtonElement>(".noteColorOptions button"),
    cancelNoteCreationBtn: getElement<HTMLButtonElement>(".cancelNoteCreationBtn"),
    addNoteBtn: getElement<HTMLButtonElement>(".addNoteBtn"),
    activityList: getElement<HTMLUListElement>(".activityList"),
    /** calendarSection: getElement<HTMLDivElement>(".calendar"),
    settingsContent: getElement<HTMLDivElement>(".settingsContent"),
    settingsNavigator: getElement<HTMLDivElement>(".settingsNavigator"), */
    settingsNavOptions: getAllElements<HTMLButtonElement>(".settingsNavItem"),
    fullNameInput: getElement<HTMLInputElement>(".fullNameInput"),
    preferredNameInput: getElement<HTMLInputElement>(".preferredNameInput"),
}