const DOM = {
     overlay: document.querySelector(".overlay"),
     askForNotifications : document.querySelector(".askForNotifications"),
     enableNotificationsBtn : document.querySelector(".enableNotificationsBtn"),
     closeNotiPopup : document.querySelector(".closeNotiPopup"),
     sidebar : document.querySelector(".sidebar"),
     sidebarBtns : document.querySelectorAll(".sidebar button"),
     hamburgerBtn : document.querySelector(".hamburgerBtn"),
     analyticsBtn : document.querySelector(".analyticsBtn"),
     whatToFocusOn : document.querySelector(".whatToFocusOn"),
     focusOnList : document.querySelector(".focusOnList"),
     header : document.querySelector(".header"),
     searchDiv : document.querySelector(".searchDiv"),
     searchBar : document.querySelector(".searchBar"),
     searchResultsMenu : document.querySelector(".searchResultsMenu"),
     dashboardBtn : document.querySelector(".dashboardBtn"),
     calendarBtn : document.querySelector(".calendarBtn"),
     dashboardContent : document.querySelector(".dashboardContent"),
     dashboardHeader : document.querySelector(".dashboardHeader"),
     agentBtn : document.querySelector(".agentBtn"),
     aiOptions : document.querySelector(".aiOptions"),
     aiOptionsList : document.querySelector(".aiOptionsList"),
     decrastinatorBtn : document.querySelector(".decrastinatorBtn"),
     customizeBtn : document.querySelector(".customizeBtn"),
     customizeDiv : document.querySelector(".customizeDiv"),
     customizeBgOptions : document.querySelectorAll(".customizeBgOptions button"),
     currentDate : document.querySelector(".currentDate"),
     dynamicGreeting : document.querySelector(".greeting"),
     expandMiniAnalyticsBtn : document.querySelector(".expandMiniAnalyticsBtn"),
     miniAnalytics : document.querySelector(".miniAnalytics"),
     workAreaSplit : document.querySelector(".workAreaSplit"),
     section1 : document.querySelector(".section1"),
     section2 : document.querySelector(".section2"),
     toDoList : document.querySelector(".toDoList"),
     toDoListHeader : document.querySelector(".toDoListHeader"),
     taskSortSelector : document.querySelector(".taskSortSelector"),
     taskViewSelector : document.querySelector(".taskViewSelector"),
     addBtn : document.querySelector(".addBtn"),
     taskCreationDiv : document.querySelector(".taskCreationDiv"),
     actualTaskCreation : document.querySelector(".actualTaskCreation"),
     taskInput : document.querySelector(".taskInput"),
     taskAttrCreation : document.querySelector(".taskAttrCreation"),
     taskPrioritySelector : document.querySelector(".taskPrioritySelector"),
     taskDateInput : document.querySelector(".taskDateInput"),
     taskTimeInput : document.querySelector(".taskTimeInput"),
     taskStatusSelector : document.querySelector(".taskStatusSelector"),
     addAndCancelButtons : document.querySelector(".addAndCancelButtons"),
     cancelTaskCreationBtn : document.querySelector(".cancelTaskCreationBtn"),
     addTaskBtn : document.querySelector(".addTaskBtn"),
     taskList : document.querySelector(".taskList"),
     noTasksYetAlert : document.querySelector(".noTasksYetAlert"),
     dropZones : document.querySelector(".dropZones"),
     toDoDropZone : document.querySelector(".toDoDropZone"),
     inProgressDropZone : document.querySelector(".inProgressDropZone"),
     allDoneDropZone : document.querySelector(".allDoneDropZone"),
     focusTimer : document.querySelector(".focusTimer"),
     taskSelectionDropdown : document.querySelector(".taskSelectionDropdown"),
     currentFocusedTask : document.querySelector(".currentFocusedTask"),
     timerMinutesDiv : document.querySelector(".timerMinutesDiv"),
     timerProgressRing : document.querySelector(".timerProgressRing"),
     timerMinutes : document.querySelector(".timerMinutes"),
     timerButtons : document.querySelector(".timerButtons"),
     lengthButtons : document.querySelectorAll(".timerLengthOptions button"),
     startTimerBtn : document.querySelector(".startTimerBtn"),
     pauseTimerBtn : document.querySelector(".pauseTimerBtn"),
     restartTimerBtn : document.querySelector(".restartTimerBtn"),
     themeBtn : document.querySelector(".themeBtn"),
     notes : document.querySelector(".notes"),
     addBtn2 : document.querySelector(".addBtn2"),
     notesList : document.querySelector(".notesList"),
     notesHeader : document.querySelector(".notesHeader"),
     noNotesYetAlert : document.querySelector(".noNotesYetAlert"),
     noteCreationDiv : document.querySelector(".noteCreationDiv"),
     noteInput : document.querySelector(".noteInput"),
     noteColorOptions : document.querySelectorAll(".noteColorOptions button"),
     cancelNoteCreationBtn : document.querySelector(".cancelNoteCreationBtn"),
     addNoteBtn : document.querySelector(".addNoteBtn"),
     activityList : document.querySelector(".activityList"),
     calendarSection: document.querySelector(".calendar"),
     analyticsContent: document.querySelector(".analyticsContent"),
     analyticsMainContent: document.querySelector(".analyticsMainContent"),
     AI_API_BASE: "http://127.0.0.1:5000",
},

export default DOM;